//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AltKategori> AltKategori { get; set; }
        public virtual DbSet<Duyuru> Duyuru { get; set; }
        public virtual DbSet<Favoriler> Favoriler { get; set; }
        public virtual DbSet<Il> Il { get; set; }
        public virtual DbSet<Ilce> Ilce { get; set; }
        public virtual DbSet<Iletisim> Iletisim { get; set; }
        public virtual DbSet<Kategori> Kategori { get; set; }
        public virtual DbSet<Kullanici> Kullanici { get; set; }
        public virtual DbSet<KullaniciBilgileri> KullaniciBilgileri { get; set; }
        public virtual DbSet<logKullanici> logKullanici { get; set; }
        public virtual DbSet<logSatinAlinan> logSatinAlinan { get; set; }
        public virtual DbSet<logSepet> logSepet { get; set; }
        public virtual DbSet<logZiyaret> logZiyaret { get; set; }
        public virtual DbSet<Marka> Marka { get; set; }
        public virtual DbSet<Mesaj> Mesaj { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<Sepet> Sepet { get; set; }
        public virtual DbSet<SepettekiUrunler> SepettekiUrunler { get; set; }
        public virtual DbSet<Siparis> Siparis { get; set; }
        public virtual DbSet<SiparisDetay> SiparisDetay { get; set; }
        public virtual DbSet<Stok> Stok { get; set; }
        public virtual DbSet<Urun> Urun { get; set; }
        public virtual DbSet<ZiyaretciMesaj> ZiyaretciMesaj { get; set; }
        public virtual DbSet<EnCokSatanUrunler> EnCokSatanUrunler { get; set; }
        public virtual DbSet<EnCokSatanUrunler4> EnCokSatanUrunler4 { get; set; }
        public virtual DbSet<EnCokSatanUrunler1> EnCokSatanUrunler1Set { get; set; }
        public virtual DbSet<GecmisSiparisler> GecmisSiparisler { get; set; }
    
        [DbFunction("Entities", "FN_OrderByBestSallers")]
        public virtual IQueryable<FN_OrderByBestSallers_Result> FN_OrderByBestSallers()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<FN_OrderByBestSallers_Result>("[Entities].[FN_OrderByBestSallers]()");
        }
    
        [DbFunction("Entities", "FN_OrderByNameASC")]
        public virtual IQueryable<FN_OrderByNameASC_Result> FN_OrderByNameASC()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<FN_OrderByNameASC_Result>("[Entities].[FN_OrderByNameASC]()");
        }
    
        [DbFunction("Entities", "FN_OrderByNameDESC")]
        public virtual IQueryable<FN_OrderByNameDESC_Result> FN_OrderByNameDESC()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<FN_OrderByNameDESC_Result>("[Entities].[FN_OrderByNameDESC]()");
        }
    
        [DbFunction("Entities", "FN_OrderByPriceASC")]
        public virtual IQueryable<FN_OrderByPriceASC_Result> FN_OrderByPriceASC()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<FN_OrderByPriceASC_Result>("[Entities].[FN_OrderByPriceASC]()");
        }
    
        [DbFunction("Entities", "FN_OrderByPriceDESC")]
        public virtual IQueryable<FN_OrderByPriceDESC_Result> FN_OrderByPriceDESC()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<FN_OrderByPriceDESC_Result>("[Entities].[FN_OrderByPriceDESC]()");
        }
    
        [DbFunction("Entities", "FN_SearchProduct")]
        public virtual IQueryable<FN_SearchProduct_Result> FN_SearchProduct(string text)
        {
            var textParameter = text != null ?
                new ObjectParameter("text", text) :
                new ObjectParameter("text", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<FN_SearchProduct_Result>("[Entities].[FN_SearchProduct](@text)", textParameter);
        }
    
        [DbFunction("Entities", "FN_OrderByBestSallers1")]
        public virtual IQueryable<FN_OrderByBestSallers1_Result> FN_OrderByBestSallers1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<FN_OrderByBestSallers1_Result>("[Entities].[FN_OrderByBestSallers1]()");
        }
    
        [DbFunction("Entities", "FN_OrderByNameASC1")]
        public virtual IQueryable<FN_OrderByNameASC1_Result> FN_OrderByNameASC1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<FN_OrderByNameASC1_Result>("[Entities].[FN_OrderByNameASC1]()");
        }
    
        [DbFunction("Entities", "FN_OrderByNameDESC1")]
        public virtual IQueryable<FN_OrderByNameDESC1_Result> FN_OrderByNameDESC1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<FN_OrderByNameDESC1_Result>("[Entities].[FN_OrderByNameDESC1]()");
        }
    
        [DbFunction("Entities", "FN_OrderByPriceASC1")]
        public virtual IQueryable<FN_OrderByPriceASC1_Result> FN_OrderByPriceASC1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<FN_OrderByPriceASC1_Result>("[Entities].[FN_OrderByPriceASC1]()");
        }
    
        [DbFunction("Entities", "FN_OrderByPriceDESC1")]
        public virtual IQueryable<FN_OrderByPriceDESC1_Result> FN_OrderByPriceDESC1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<FN_OrderByPriceDESC1_Result>("[Entities].[FN_OrderByPriceDESC1]()");
        }
    
        [DbFunction("Entities", "FN_SearchProduct1")]
        public virtual IQueryable<FN_SearchProduct1_Result> FN_SearchProduct1(string text)
        {
            var textParameter = text != null ?
                new ObjectParameter("text", text) :
                new ObjectParameter("text", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<FN_SearchProduct1_Result>("[Entities].[FN_SearchProduct1](@text)", textParameter);
        }
    
        [DbFunction("Entities", "FN_OrderByBestSallers2")]
        public virtual IQueryable<FN_OrderByBestSallers2_Result> FN_OrderByBestSallers2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<FN_OrderByBestSallers2_Result>("[Entities].[FN_OrderByBestSallers2]()");
        }
    
        [DbFunction("Entities", "FN_OrderByBestSallersNew")]
        public virtual IQueryable<FN_OrderByBestSallersNew_Result> FN_OrderByBestSallersNew()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<FN_OrderByBestSallersNew_Result>("[Entities].[FN_OrderByBestSallersNew]()");
        [DbFunction("Entities", "FN_OrderByBestSallers3")]
        public virtual IQueryable<FN_OrderByBestSallers3_Result> FN_OrderByBestSallers3()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<FN_OrderByBestSallers3_Result>("[Entities].[FN_OrderByBestSallers3]()");
        }
    
        [DbFunction("Entities", "EnCokEtkilesimAlanAltKategori")]
        public virtual IQueryable<EnCokEtkilesimAlanAltKategori_Result> EnCokEtkilesimAlanAltKategori(Nullable<int> kullaniciId)
        {
            var kullaniciIdParameter = kullaniciId.HasValue ?
                new ObjectParameter("kullaniciId", kullaniciId) :
                new ObjectParameter("kullaniciId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<EnCokEtkilesimAlanAltKategori_Result>("[Entities].[EnCokEtkilesimAlanAltKategori](@kullaniciId)", kullaniciIdParameter);
        }
    
        [DbFunction("Entities", "EnCokEtkilesimAlanAltKategori1")]
        public virtual IQueryable<EnCokEtkilesimAlanAltKategori1_Result> EnCokEtkilesimAlanAltKategori1(Nullable<int> kullaniciId)
        {
            var kullaniciIdParameter = kullaniciId.HasValue ?
                new ObjectParameter("kullaniciId", kullaniciId) :
                new ObjectParameter("kullaniciId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<EnCokEtkilesimAlanAltKategori1_Result>("[Entities].[EnCokEtkilesimAlanAltKategori1](@kullaniciId)", kullaniciIdParameter);
        }
    }
}
