//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class logZiyaret
    {
        public int logZiyaretID { get; set; }
        public Nullable<System.DateTime> gunlukTarih { get; set; }
        public Nullable<int> haftalikTarih { get; set; }
        public Nullable<int> gunlukZiyaret { get; set; }
        public Nullable<int> haftalikZiyaret { get; set; }
        public Nullable<int> toplamZiyaret { get; set; }
    }
}
