//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiparisDetay
    {
        public int siparisID { get; set; }
        public Nullable<System.DateTime> siparisTarihi { get; set; }
        public Nullable<decimal> siparisTutari { get; set; }
    
        public virtual Siparis Siparis { get; set; }
    }
}
